### ISSUE TITLE
Basic YAML Parsing

### ISSUE THREAD

**Issue by jordanstites** [TheYamsSIUE/Yamlyzer#3]
Find a python YAML parser and have it open the compiled YAML file and do basic parsing

**Comment by riveeenxu** [comment]
Add subtask of setting up the file upload module along with the yaml parsing module

**Comment by riveeenxu** [comment]
The template html and the view.py file in yamlview are modified to make the file->open button functional. A post request is now created by triggering the confirm button and handled by view.py which sends it to the PyYAML handler to convert into raw, parsed dictionary objects. The success of file upload can be confirmed from the server console but also the file information modal top-right of the current template page.
